[package]
name = "ff4"
version = "0.1.0"
authors = ["Erik Gilling <konkers@konkers.net>"]
edition = "2018"

[features]
ci_tests = []

[dependencies]
lazy_static = "1.2.0"
nom = "4.1"
serde = "^1.0.59"
serde_derive = "^1.0.59"
serde_json = "1.0"
simple-error = "0.1"

